# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yzWWwMDUBvjRTFikXyKaYyy8GIpy_Sd
"""

import streamlit as st
import random
import string

st.set_page_config(page_title="مولد كلمات مرور آمنة", page_icon="🔐", layout="centered")
st.title("🔐 مولد كلمات مرور آمنة")
st.markdown("""
### 🎯 خصص كلمة المرور حسب رغبتك
اختر الخصائص التي تريدها، واضغط على الزر لإنشاء كلمة مرور آمنة.
""")

length = st.slider("🔢 اختر طول كلمة المرور", 8, 50, 12)

st.markdown("**اختر أنواع الحروف:**")
use_uppercase = st.checkbox("🔠 أحرف كبيرة (A-Z)", value=True)
use_lowercase = st.checkbox("🔡 أحرف صغيرة (a-z)", value=True)
use_digits = st.checkbox("🔢 أرقام (0-9)", value=True)
use_symbols = st.checkbox("🔣 رموز خاصة (!@#$%)", value=True)

characters = ""
if use_uppercase:
    characters += string.ascii_uppercase
if use_lowercase:
    characters += string.ascii_lowercase
if use_digits:
    characters += string.digits
if use_symbols:
    characters += string.punctuation

if st.button("🚀 إنشاء كلمة مرور"):
    if not characters:
        st.warning("⚠️ يرجى اختيار نوع واحد على الأقل من الحروف.")
    else:
        password = ''.join(random.choice(characters) for _ in range(length))
        st.success("🔑 كلمة المرور الخاصة بك:")
        st.code(password, language="")
        st.success("✅ تم الإنشاء! لا تنسخها في مكان آمن.")

st.markdown("---")
st.caption("تم الإنشاء بواسطة فصعوون ❤")